language: go
go:
  - 1.7.1
before_install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
script:
  - go test -v $(go list ./... | grep -v /vendor/)
after_success:
  - sh `pwd`/scripts/coverage --coveralls
